# Conda environment description:
# * Install miniconda
# * Run `conda env create -f environment.yml`
# * Run `. activate WrfUtils`

name: WrfUtils
dependencies:
- numpy=1.11.*
- netcdf4=1.2.*
- python=2.7.*
- pyyaml=3.*
