# Conda environment description:
# * Install miniconda
# * Run `conda env create -f environment.yml`
# * Run `. activate WrfUtils`

name: WrfUtils3
dependencies:
  # Basic python
  - python=3.5.*
  - pyyaml=3.*

  # Scientific
  - numpy=1.11.*
  - netcdf4=1.2.*
  - matplotlib=1.5.*
  
  # Persistence
  - sqlalchemy=1.0.*
  - psycopg2=2.6.*
