# Conda environment description:
# * Install miniconda
# * Run `conda env create`
# * Run `conda activate Wiski`

# 2016.11.03: Upgrading gdal causes all kinds of dependency problems in conda
# 2016.11.03: Upgrading shapely makes Polygon not hasheable so code to avoid duplicates needs to be updated

name: Wiski
dependencies:
  # Basic python
  - python=3.7.*
  - ipython
  - pyyaml=5.*

  # Scientific
  - numpy=1.16.*
  - scipy=1.2.*
  - netcdf4=1.4.*
  - matplotlib=3.0.*

  # Geometry and geography
  - basemap=1.2.*
  - basemap-data-hires=1.2.*
  - shapely=1.6.*
  - gdal=2.3.*

  # Other
  - pytz  # Always latest version
