# Conda environment description:
# * Install miniconda
# * Run `conda env create -f environment.yml`
# * Run `. activate DropDigits`

# 2016.11.03: Upgrading gdal causes all kinds of dependency problems in conda
# 2016.11.03: Upgrading shapely makes Polygon not hasheable so code to avoid duplicates needs to be updated

name: Wiski
dependencies:
  # Basic python
  - python=2.7.*
  - pyyaml=3.*

  # Scientific
  - numpy=1.9.*
  - scipy=0.15.*
  - netcdf4=1.1.*
  - matplotlib=1.4.*

  # Geometry and geography
  - basemap=1.0.*
  - shapely=1.5.*
  - gdal=1.11.*

  # Missing gdal dependency
  - krb5=1.13.*
  - proj4=4.9.*
