# Conda environment description:
# * Install miniconda
# * Run `conda env create -f environment.yml`
# * Run `. activate DropDigits`

name: DropDigits

channels:
  - defaults
  - conda-forge

dependencies:
  # Basic python
  - python=3.6.*
  - pyyaml=3.*

  # Scientific
  - numpy=1.13.*
  - netcdf4=1.3

  # Development
  - pytest=3.2.*
  - pytest-cov=2.5.*
