# Conda environment description:
# * Install miniconda
# * Run `conda env create -f environment.yml`
# * Run `. activate DropDigits3`

name: DropDigits3
dependencies:
  # Basic python
  - python=3.5.*
  - pyyaml=3.*

  # Scientific
  - numpy=1.11.*
  - netcdf4=1.2.*
