# Conda environment description:
# * Install miniconda
# * Run `conda env create -f environment.yml`
# * Run `. activate DropDigits`

name: DropDigits
dependencies:
  # Basic python
  - python=2.7.*
  - pyyaml=3.*

  # Scientific
  - numpy=1.11.*
  - netcdf4=1.2.*
