# Conda environment description:
# * Install miniconda
# * Run `conda env create -f environment.yml`
# * Run `. activate DropDigits`

name: DropDigits
dependencies:
  # Basic python
  - python=3.5.*    # There is no netcdf4=1.2.2 for python=3.6 (2017.03.07)
  - pyyaml=3.*

  # Scientific
  - numpy=1.11.*
  - netcdf4=1.2.2   # 1.2.4 has no ncdump! (2017.03.07)
