# Conda environment description:
# * Install miniconda
# * Run `conda env create -f environment.yml`
# * Run `. activate DropDigits`

name: DropDigits

channels:
  - defaults
  - conda-forge

dependencies:
  # Basic python
  - python=3.7.*
  - ipython
  - pyyaml=5.*

  # Scientific
  - numpy=1.16.*
  - netcdf4=1.4.*

  # Development
  - pytest=5.3.*
  - pytest-cov=2.8.*
