stations: 'iceland.%'
station_metadata: 'station_data.yml'
store_dir: 'output'
output_template: '{analysis_date:%Y-%m-%dT%H:%M:%S}/pf-{ref}.csv'
spinup: 3


# As an alternative to stations+station_metadata, you can define the stations you want to have point forecasts for directly in this file:
#stations:
#  - {lat: 51.1052, lon: 17.0889, name: Wrocław, ref: wroclaw.uwr}
#  - {lat: 50.865, lon: 16.708, name: Ślęża, ref: wroclaw.sleza}
