version: 1

formatters:
  simple:
    format: '%(asctime)s | %(levelname)7s | %(filename)s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  complete:
    format: '%(asctime)s | %(levelname)7s | %(filename)s:%(lineno)4d | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: complete
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ./pf.log
    maxBytes: 10485760
    backupCount: 3
  errors:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: simple
    filename: ./pf_errors.log
    maxBytes: 10485760
    backupCount: 3


root:
  level: INFO
  handlers: [console,file,errors]
loggers:
  belgingur:
    level: DEBUG
    propagate: True
  sqlalchemy.engine:
    level: WARN
    propagate: True
  sqlalchemy.pool:
    level: INFO
    propagate: True

